# Generated by Django 2.1.7 on 2019-04-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('nutriscore', models.CharField(max_length=1)),
                ('image_url', models.URLField()),
                ('id_category', models.IntegerField()),
                ('id_subcategory', models.IntegerField()),
            ],
        ),
    ]
