# Generated by Django 2.2.2 on 2019-06-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('nutriscore', models.CharField(max_length=1)),
                ('image_url', models.URLField()),
                ('purchase_places', models.CharField(max_length=50)),
                ('calories_100g', models.FloatField()),
                ('acides_gras_saturees_100g', models.FloatField()),
                ('glucides_100g', models.FloatField()),
                ('sucres_100g', models.FloatField()),
                ('fibres_100g', models.FloatField()),
                ('proteines_100g', models.FloatField()),
                ('sel_100g', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
    ]
