# Generated by Django 2.2.2 on 2019-06-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lipides_100g',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='acides_gras_saturees_100g',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='calories_100g',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='fibres_100g',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='glucides_100g',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteines_100g',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='sel_100g',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='sucres_100g',
            field=models.FloatField(default=-1),
        ),
    ]
