# Generated by Django 2.1.7 on 2019-04-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('id_subcategory', models.IntegerField()),
                ('subcategory', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('nutriscore', models.CharField(max_length=1)),
                ('image_url', models.URLField()),
                ('id_category', models.IntegerField()),
                ('id_subcategory', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Prodcut',
        ),
    ]
