# Generated by Django 2.2.2 on 2019-06-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190620_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='acides_gras_saturees_100g',
            new_name='carbohydrates_100g',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='calories_100g',
            new_name='energy_100g',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='fibres_100g',
            new_name='fat_100g',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='glucides_100g',
            new_name='fibers_100g',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='lipides_100g',
            new_name='proteins_100g',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='proteines_100g',
            new_name='salt_100g',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sel_100g',
            new_name='saturated_fats_100g',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sucres_100g',
            new_name='sugars_100g',
        ),
    ]
