# Generated by Django 2.2 on 2019-04-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190424_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_category',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_subcategory',
            field=models.IntegerField(default=-1),
        ),
    ]
