# Generated by Django 2.2.2 on 2019-06-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190429_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
